name: Soroban CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apps/soroban/**'
      - '.github/workflows/soroban-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'apps/soroban/**'
      - '.github/workflows/soroban-ci.yml'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  lint-and-test:
    name: Lint and Test Soroban Contracts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/soroban

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install Soroban CLI
        run: |
          cargo install --locked soroban-cli --features opt

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            apps/soroban/target/
          key: ${{ runner.os }}-cargo-soroban-${{ hashFiles('apps/soroban/**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-soroban-
            ${{ runner.os }}-cargo-

      - name: Check Rust formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy linting
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --verbose

      - name: Build contracts
        run: cargo build --release

      - name: Build optimized contracts
        run: |
          if [ -f "Cargo.toml" ]; then
            soroban contract build
          fi

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/soroban

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            apps/soroban/target/
          key: ${{ runner.os }}-cargo-audit-${{ hashFiles('apps/soroban/**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-audit-
            ${{ runner.os }}-cargo-

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run security audit
        run: |
          if [ -f "Cargo.toml" ]; then
            cargo audit
          fi

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: lint-and-test
    defaults:
      run:
        working-directory: ./apps/soroban

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Soroban CLI
        run: |
          cargo install --locked soroban-cli --features opt

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            apps/soroban/target/
          key: ${{ runner.os }}-cargo-integration-${{ hashFiles('apps/soroban/**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-integration-
            ${{ runner.os }}-cargo-

      - name: Start Soroban local network
        run: |
          soroban network start local &
          sleep 10

      - name: Run all tests
        run: |
          if [ -f "Cargo.toml" ]; then
            cargo test --verbose
          fi

      - name: Stop Soroban local network
        run: |
          soroban network stop local || true 